if (NOT pybind11_FOUND)
    EXECUTE_PROCESS(COMMAND bash "-c" "pip show pybind11 | grep site-packages | awk '{printf \"%s\", $2}'" OUTPUT_VARIABLE PIP_DIR)
    find_package(pybind11 REQUIRED CONFIG PATHS "${PIP_DIR}/pybind11/share/cmake/pybind11/" NO_DEFAULT_PATH)
endif ()
if (NOT pybind11_FOUND)
    message(FATAL_ERROR "can't find pybind11")
else ()
    message(STATUS "pybind11 inc_dirs: ${pybind11_INCLUDE_DIRS}")
    message(STATUS "pybind11 inc_dir: ${pybind11_INCLUDE_DIR}")
    message(STATUS "pybind11 libs: ${pybind11_DIR}")
endif ()